// AUTO-GENERATED from piano_federaziende_2026-04-18.xlsx
export const FEDER_LOOKUP = {
  "Acea Comparatore|Comparatore CLUSTER B|Privato|Gas": { base: 75, rid: 16 },
  "Acea Comparatore|Comparatore CLUSTER A|Privato|Gas": { base: 95, rid: 16 },
  "Acea Comparatore|Comparatore CLUSTER C|Privato|Gas": { base: 50, rid: 16 },
  "Acea Comparatore|Comparatore CLUSTER C|Privato|Energia Elettrica": { base: 50, rid: 16 },
  "Acea Comparatore|Comparatore CLUSTER B|Privato|Energia Elettrica": { base: 75, rid: 16 },
  "Acea Comparatore|Comparatore CLUSTER A|Privato|Energia Elettrica": { base: 95, rid: 16 },
  "Alperia|CLEAR PRIME|Privato|Energia Elettrica": { base: 35, rid: 16 },
  "Alperia|NEVES|Business|Gas": { base: 50, rid: 16 },
  "Alperia|PURE STANDARD|Privato|Energia Elettrica": { base: 15, rid: 16 },
  "Alperia|PREMIUM|Privato|Energia Elettrica": { base: 55, rid: 16 },
  "Alperia|NEVES|Business|Energia Elettrica": { base: 50, rid: 16 },
  "Alperia|BRAIES|Business|Gas": { base: 35, rid: 16 },
  "Alperia|PURE STANDARD|Privato|Gas": { base: 15, rid: 16 },
  "Alperia|PRO|Privato|Energia Elettrica": { base: 45, rid: 16 },
  "Alperia|PRO|Privato|Gas": { base: 45, rid: 16 },
  "Alperia|RESIA|Business|Gas": { base: 30, rid: 16 },
  "Alperia|CLEAR PRIME|Privato|Gas": { base: 35, rid: 16 },
  "Alperia|PREMIUM|Privato|Gas": { base: 55, rid: 16 },
  "Alperia|RESIA|Business|Energia Elettrica": { base: 25, rid: 16 },
  "Alperia|BRAIES|Business|Energia Elettrica": { base: 30, rid: 16 },
  "Argos|Base|Privato|Energia Elettrica": { base: 50, rid: 10 },
  "Argos|Base|Privato|Gas": { base: 50, rid: 10 },
  "Estra Energie|Base|Privato|Energia Elettrica": { base: 75, rid: 5 },
  "Estra Energie|Base|Business|Gas": { base: 80, rid: 5 },
  "Estra Energie|Base|Privato|Gas": { base: 75, rid: 5 },
  "Estra Energie|Base|Business|Energia Elettrica": { base: 80, rid: 5 },
  "Fastweb Energia Comparatore|Luce Fix|Privato|Energia Elettrica": { base: 80, rid: 0 },
  "Hera Comm|Hera Power Rid Da 50.001 a 300.000 kWh|Business|Energia Elettrica": { base: 191, rid: 32 },
  "Hera Comm|Base|Privato|Gas": { base: 45, rid: 20 },
  "Hera Comm|Base|Privato|Energia Elettrica": { base: 45, rid: 20 },
  "Hera Comm|Hera Power Da 0 a 50.000 kWh|Business|Energia Elettrica": { base: 60, rid: 20 },
  "Hera Comm|Hera Gas Da 10.001 a 50.000 m3|Business|Gas": { base: 191, rid: 32 },
  "Hera Comm|Hera Gas Da 0 a 10.000 m3|Business|Gas": { base: 60, rid: 20 },
  "I PHONE 17|iPhone 17 256 GB Black 5G SMART|Business|Noleggio Tech": { base: 67, rid: 0 },
  "I PHONE 17|iPhone 17 256 GB Black 5G EASY|Business|Noleggio Tech": { base: 40, rid: 0 },
  "I PHONE 17|iPhone 17 256 GB Black 5G TOP|Business|Noleggio Tech": { base: 75, rid: 0 },
  "I PHONE 17|iPhone 17 512 GB Black5G  TOP|Business|Noleggio Tech": { base: 91, rid: 0 },
  "I PHONE 17|iPhone 17 512 GB Black5G  EASY|Business|Noleggio Tech": { base: 45, rid: 0 },
  "I PHONE 17|iPhone 17 512 GB Black5G  SMART|Business|Noleggio Tech": { base: 75, rid: 0 },
  "I PHONE 17|iPhone 17 512 GB Black5G  PREMIUM|Business|Noleggio Tech": { base: 107, rid: 0 },
  "I PHONE 17|iPhone 17 256 GB Black 5G PREMIUM|Business|Noleggio Tech": { base: 91, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro 512 GB  Deep Blue 5G SMART|Business|Noleggio Tech": { base: 83, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro Max 1 TB  Deep Blue  5G Premium|Business|Noleggio Tech": { base: 139, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro 256 GB Deep Blue 5G  TOP|Business|Noleggio Tech": { base: 99, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro Max 1 TB  Deep Blue  5G SMART|Business|Noleggio Tech": { base: 91, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro 512 GB  Deep Blue 5G PREMIUM|Business|Noleggio Tech": { base: 131, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro 1 TB Deep Blue 5G SMART|Business|Noleggio Tech": { base: 91, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro Max 256 GB  Deep Blue 5G TOP|Business|Noleggio Tech": { base: 99, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro 512 GB  Deep Blue 5G TOP|Business|Noleggio Tech": { base: 99, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro 1 TB Deep Blue 5G PREMIUM|Business|Noleggio Tech": { base: 139, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro 512 GB  Deep Blue 5G EASY|Business|Noleggio Tech": { base: 55, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro Max 512 GB  Deep Blue 5G TOP|Business|Noleggio Tech": { base: 99, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro Max 256 GB  Deep Blue 5G SMART|Business|Noleggio Tech": { base: 83, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro Max 2 TB Deep Blue 5G SMART|Business|Noleggio Tech": { base: 99, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro 1 TB Deep Blue 5G TOP|Business|Noleggio Tech": { base: 107, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro Max 2 TB Deep Blue 5G TOP|Business|Noleggio Tech": { base: 115, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro 1 TB Deep Blue 5G  EASY|Business|Noleggio Tech": { base: 67, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro Max 1 TB  Deep Blue  5G TOP|Business|Noleggio Tech": { base: 107, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro Max 512 GB  Deep Blue 5G SMART|Business|Noleggio Tech": { base: 83, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro 256 GB Deep Blue 5G   EASY|Business|Noleggio Tech": { base: 55, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro Max 256 GB  Deep Blue 5G Premium|Business|Noleggio Tech": { base: 131, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro Max 512 GB  Deep Blue 5G EASY|Business|Noleggio Tech": { base: 55, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro Max 2 TB Deep Blue 5G EASY|Business|Noleggio Tech": { base: 75, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro Max 2 TB Deep Blue 5G Premium|Business|Noleggio Tech": { base: 155, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro Max 1 TB  Deep Blue  5G EASY|Business|Noleggio Tech": { base: 67, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro Max 256 GB  Deep Blue 5G EASY|Business|Noleggio Tech": { base: 55, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro Max 512 GB  Deep Blue 5G Premium|Business|Noleggio Tech": { base: 131, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro 256 GB Deep Blue 5G  SMART|Business|Noleggio Tech": { base: 83, rid: 0 },
  "I Phone 17 Pro|iPhone 17 Pro 256 GB Deep Blue 5G  PREMIUM|Business|Noleggio Tech": { base: 131, rid: 0 },
  "Illumia Comparatore|Base|Privato|Energia Elettrica": { base: 50, rid: 5 },
  "Illumia Comparatore|Base (copia)|Privato|Gas": { base: 50, rid: 5 },
  "Iren Comparatore|Promo Switch Bassa Marginalità|Privato|Gas": { base: 60, rid: 10 },
  "Iren Comparatore|Promo Switch Bassa Marginalità|Privato|Energia Elettrica": { base: 60, rid: 10 },
  "Iren Mercato Libero|Promo Switch Bassa Marginalità|Privato|Gas": { base: 50, rid: 16 },
  "Iren Mercato Libero|Base|Privato|Gas": { base: 60, rid: 16 },
  "Iren Mercato Libero|Base|Business|Gas": { base: 55, rid: 10 },
  "Iren Mercato Libero|Base|Privato|Luce": { base: 60, rid: 16 },
  "Iren Mercato Libero|Base|Business|Energia Elettrica": { base: 55, rid: 10 },
  "Noleggio A Lungo Termine|Base|Privato|Noleggio A Lungo Termine": { base: 115, rid: 0 },
  "Noleggio A Lungo Termine|Base|Business|Noleggio A Lungo Termine": { base: 115, rid: 0 },
  "Noleggio Stampanti|BROTHER - mfc-L6915 dw SCONTATA|Business|Altro": { base: 200, rid: 0 },
  "Noleggio Stampanti|BROTHER - HL-L5210DN SCONTATA|Business|Altro": { base: 200, rid: 0 },
  "Noleggio Stampanti|CANON - iSENSYS X C 1333i SCONTATA|Business|Altro": { base: 400, rid: 0 },
  "Noleggio Stampanti|BROTHER - mfc-j5955 dw|Business|Altro": { base: 150, rid: 0 },
  "Noleggio Stampanti|CANON - IMAGE RUNNER 3326i|Business|Altro": { base: 700, rid: 0 },
  "Noleggio Stampanti|CANON - iSENSYS X C 1333p SCONTATA|Business|Altro": { base: 200, rid: 0 },
  "Noleggio Stampanti|EPSON - WF C8101RD|Business|Altro": { base: 300, rid: 0 },
  "Noleggio Stampanti|CANON - IMAGE RUNNER ADVANCE DX C 3922i SCONTATA|Business|Altro": { base: 400, rid: 0 },
  "Noleggio Stampanti|BROTHER - HL-L9430CDW|Business|Altro": { base: 200, rid: 0 },
  "Noleggio Stampanti|CANON - iSENSYS X C 1333i|Business|Altro": { base: 400, rid: 0 },
  "Noleggio Stampanti|BROTHER - MFC-L9635|Business|Altro": { base: 400, rid: 0 },
  "Noleggio Stampanti|CANON - iSENSYS X C 1333p|Business|Altro": { base: 300, rid: 0 },
  "Noleggio Stampanti|BROTHER - mfc-j4535dwxl|Business|Altro": { base: 100, rid: 0 },
  "Noleggio Stampanti|BROTHER - MFC-L5710DW SCONTATA|Business|Altro": { base: 200, rid: 0 },
  "Noleggio Stampanti|EPSON - AM C800R|Business|Altro": { base: 200, rid: 0 },
  "Noleggio Stampanti|CANON - IMAGE RUNNER 3326i SCONTATA|Business|Altro": { base: 400, rid: 0 },
  "Noleggio Stampanti|EPSON - AM C4000|Business|Altro": { base: 800, rid: 0 },
  "Noleggio Stampanti|BROTHER - mfc-j4335dwxl SCONTATA|Business|Altro": { base: 75, rid: 0 },
  "Noleggio Stampanti|BROTHER - mfc-j6957 dw|Business|Altro": { base: 400, rid: 0 },
  "Noleggio Stampanti|BROTHER - HL-L6415 DW SCONTATA|Business|Altro": { base: 150, rid: 0 },
  "Noleggio Stampanti|CANON - IMAGE RUNNER ADVANCE DX C 3922i|Business|Altro": { base: 800, rid: 0 },
  "Noleggio Stampanti|EPSON - AM C400|Business|Altro": { base: 400, rid: 0 },
  "Noleggio Stampanti|BROTHER - HL-L5210DN|Business|Altro": { base: 300, rid: 0 },
  "Noleggio Stampanti|BROTHER - MFC-L5710DW|Business|Altro": { base: 400, rid: 0 },
  "Noleggio Stampanti|BROTHER - MFC-L9635 SCONTATA|Business|Altro": { base: 300, rid: 0 },
  "Noleggio Stampanti|BROTHER - HL-L6415 DW|Business|Altro": { base: 200, rid: 0 },
  "Noleggio Stampanti|BROTHER - mfc-L6915 dw|Business|Altro": { base: 300, rid: 0 },
  "Noleggio Stampanti|BROTHER - HL-L9430CDW SCONTATA|Business|Altro": { base: 150, rid: 0 },
  "Nova Energy|SUNPOWER PERFORMANCE 7 Trifase 5+10|Privato|Fotovoltaico": { base: 899, rid: 0 },
  "Nova Energy|SUNPOWER PERFORMANCE 7 Trifase 5+10 Business|Business|Fotovoltaico": { base: 899, rid: 0 },
  "Nova Energy|SUNPOWER PERFORMANCE 7 Monofase 5+10|Privato|Fotovoltaico": { base: 800.6, rid: 0 },
  "Nova Energy|SUNPOWER PERFORMANCE 7 Trifase 8+10 Business|Business|Fotovoltaico": { base: 1099, rid: 0 },
  "Nova Energy|SUNPOWER PERFORMANCE 7 Monofase 6+10|Privato|Fotovoltaico": { base: 859, rid: 0 },
  "Nova Energy|SUNPOWER PERFORMANCE 7 Trifase Business 6+10|Business|Fotovoltaico": { base: 955, rid: 0 },
  "Nova Energy|SUNPOWER PERFORMANCE 7 Trifase 10+10|Privato|Fotovoltaico": { base: 1243, rid: 0 },
  "Nova Energy|SUNPOWER PERFORMANCE 7 Trifase 10+10 Business|Business|Fotovoltaico": { base: 1243, rid: 0 },
  "Nova Energy|SUNPOWER PERFORMANCE 7 Monofase 6+10 Business|Business|Fotovoltaico": { base: 859, rid: 0 },
  "Nova Energy|SUNPOWER PERFORMANCE 7 Monofase 8+10 Business|Business|Fotovoltaico": { base: 971, rid: 0 },
  "Nova Energy|SUNPOWER PERFORMANCE 7 Monofase 10+10 Business|Privato|Fotovoltaico": { base: 1091, rid: 0 },
  "Nova Energy|SUNPOWER PERFORMANCE 7 Monofase 8+10|Privato|Fotovoltaico": { base: 971, rid: 0 },
  "Nova Energy|SUNPOWER PERFORMANCE 7 Trifase 8+10|Privato|Fotovoltaico": { base: 1099, rid: 0 },
  "Nova Energy|SUNPOWER PERFORMANCE 7 Trifase 6+10|Privato|Fotovoltaico": { base: 955, rid: 0 },
  "Nova Energy|SUNPOWER PERFORMANCE 7 Monofase Business 5+10|Business|Fotovoltaico": { base: 800.6, rid: 0 },
  "Nova Energy|SUNPOWER PERFORMANCE 7 Monofase 10+10|Privato|Fotovoltaico": { base: 1091, rid: 0 },
  "PLENITUDE COMPARATORE|Base|Privato|Energia Elettrica": { base: 50, rid: 20 },
  "PLENITUDE COMPARATORE|Base|Privato|Gas": { base: 50, rid: 20 },
  "PLENITUDE FIBRA|Base|Privato|Telefonia": { base: 45, rid: 20 },
  "Pulsee|Value|Privato|Energia Elettrica": { base: 67, rid: 0 },
  "Pulsee|Comparatore Easy|Privato|Energia Elettrica": { base: 30, rid: 0 },
  "Pulsee|Value|Privato|Gas": { base: 67, rid: 0 },
  "Pulsee|Comparatore Easy|Privato|Gas": { base: 30, rid: 0 },
  "Pulsee|Smart|Privato|Gas": { base: 87, rid: 0 },
  "Pulsee|Comparatore Partner|Privato|Energia Elettrica": { base: 40, rid: 0 },
  "Pulsee|Comparatore Partner|Privato|Gas": { base: 40, rid: 0 },
  "Pulsee|Smart|Privato|Energia Elettrica": { base: 87, rid: 0 },
  "SAMSUNG GALAXY S25 ULTRA|Samsung S25 Ultra 512 GB / 12 GB    Top|Business|Noleggio Tech": { base: 123, rid: 0 },
  "SAMSUNG GALAXY S25 ULTRA|Samsung S25 Ultra 512 GB / 12 GB   Premium|Business|Noleggio Tech": { base: 155, rid: 0 },
  "Sinergy|Base|Privato|Gas": { base: 71, rid: 8 },
  "Sinergy|Base|Business|Gas": { base: 75, rid: 8 },
  "Sinergy|Base|Business|Energia Elettrica": { base: 75, rid: 8 },
  "Sinergy|Base|Privato|Energia Elettrica": { base: 71, rid: 8 },
  "Sky|Triple Play [ Sky WiFi + Sky TV con Decoder ]|Privato|Telefonia": { base: 243, rid: 0 },
  "Sky|WiFi|Business|Telefonia": { base: 155, rid: 0 },
  "Sky|NEGOZIO & UFFICIO|Business|Telefonia": { base: 35, rid: 0 },
  "Sky|Promo con canone|Business|Telefonia": { base: 187, rid: 0 },
  "Sky|Sky TV con Intrattenimento Plus a 14,90€ / 15,90€ / 17,90€|Privato|Telefonia": { base: 126.2, rid: 0 },
  "Sky|Sky Wifi Only con Carte Prepagate|Privato|Telefonia": { base: 99, rid: 0 },
  "Sky|Sky Wifi Only con CC/RID|Privato|Telefonia": { base: 123, rid: 0 },
  "Sky|Sky TV Only|Privato|Telefonia": { base: 180.6, rid: 0 },
  "Sky|Triple Play Sky WiFi + Sky TV con Decoder|Privato|Telefonia": { base: 200, rid: 0 },
  "Sorgenia|Borsa Light|Business|Energia Elettrica": { base: 85, rid: 10 },
  "Tim|Comparatore Tim FTTC NIP|Privato|Telefonia": { base: 99, rid: 0 },
  "Tim|Comparatore Tim FTTH ULL|Privato|Telefonia": { base: 123, rid: 0 },
  "Tim|Comparatore Tim FTTC ULL|Privato|Telefonia": { base: 115, rid: 0 },
  "Tim|Mobile|Business|Telefonia": { base: 40, rid: 0 },
  "Tim|Comparatore Tim FTTH NIP|Privato|Telefonia": { base: 107, rid: 0 },
  "Tim|Base|Business|Telefonia": { base: 131, rid: 0 },
  "WiCity|HI MAX/ULTRAWEB/HI CITY|Business|Telefonia": { base: 115, rid: 0 },
  "WiCity|HIMAX/ULTRAWEB/GIGAHOME|Privato|Telefonia": { base: 55, rid: 0 },
  "WIND ENERGIA|Base|Privato|Energia Elettrica": { base: 35, rid: 28 },
  "WIND ENERGIA|Base|Business|Gas": { base: 63, rid: 10.5 },
  "WIND ENERGIA|Base|Business|Energia Elettrica": { base: 63, rid: 10.5 },
  "WIND ENERGIA|Base|Privato|Gas": { base: 35, rid: 28 },
  "Wind Tre|FTTC FWA|Privato|Telefonia": { base: 139, rid: 0 },
  "Wind Tre|FTTH|Privato|Telefonia": { base: 155, rid: 0 },
  "Wind Tre|Promo Sconto Convergenza Business|Business|Telefonia": { base: 135, rid: 0 },
  "Wind Tre|Mobile|Privato|Telefonia": { base: 7, rid: 0 },
  "Wind Tre|Promo Sconto Convergenza|Privato|Telefonia": { base: 75, rid: 0 },
};
